services:
  - type: web
    name: school-management-system
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_KEY
        value: base64:KcLcS3WBI4/fRo9NYW6R6MH7b1o4cIdpnvyADAwjy0Y=
      - key: APP_DEBUG
        value: true
      - key: APP_URL
        value: https://school-management-system-m2c1.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql.internal
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: school
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 